

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."create_user_on_signup"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$BEGIN
    INSERT INTO public.user (id,email,display_name)
    VALUES (
      NEW.id,
      new.raw_user_meta_data ->>'email',
      new.raw_user_meta_data ->>'name'
    );

    RETURN NEW;
END;$$;


ALTER FUNCTION "public"."create_user_on_signup"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Agreements" (
    "agreement_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "version" "text" NOT NULL,
    "ip_address" "text",
    "agent" "jsonb",
    "job_id" "uuid",
    "user_id" "uuid" DEFAULT "auth"."uid"()
);


ALTER TABLE "public"."Agreements" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Applicants" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "unique_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "seeker_id" "uuid" DEFAULT "auth"."uid"(),
    "job_id" "uuid",
    "name" "text",
    "status" "text",
    "payment_status" "text",
    "is_confirmed" boolean DEFAULT false,
    "payment_reference" "text",
    "payment_date" timestamp with time zone
);


ALTER TABLE "public"."Applicants" OWNER TO "postgres";


ALTER TABLE "public"."Applicants" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Applicants_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."CompanyInfo" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "type" "text",
    "website" "text",
    "description" "text",
    "logo" "text",
    "unique_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "position_in_company" "text"
);


ALTER TABLE "public"."CompanyInfo" OWNER TO "postgres";


ALTER TABLE "public"."CompanyInfo" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CompanyInfo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Education" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "level" "text",
    "school_name" "text",
    "field" "text",
    "year" "text",
    "unique_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."Education" OWNER TO "postgres";


ALTER TABLE "public"."Education" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Education_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Experience" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "company_name" "text",
    "title" "text",
    "start_date" "date",
    "end_date" "date",
    "cv" "text",
    "cover_letter" "text",
    "unique_id" "uuid" DEFAULT "auth"."uid"() NOT NULL
);


ALTER TABLE "public"."Experience" OWNER TO "postgres";


ALTER TABLE "public"."Experience" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Experience_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Jobs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    "description" "text",
    "type" "text",
    "location" "text",
    "responsibilities" "text",
    "who_we_are" "text",
    "minsalary" "text",
    "uid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "recruiter" "uuid" DEFAULT "auth"."uid"(),
    "category" "text",
    "maxsalary" "text",
    "duration" "text",
    "skills" "text"[],
    "deadline" "date",
    "accomodation" "text",
    "company_name" "text",
    "payment_type" "text",
    "signup_fee" "text",
    "limit" smallint,
    "city" "text",
    "country" "text",
    "provides_certificate" boolean,
    "start_date" "date",
    "state" "text",
    "training_mode" "text",
    "teaching_method" "text",
    "learning_outcomes" "text",
    "scheduling" "text",
    "outcomes" "text",
    "trainer_credentials" "text",
    "settlement" "text",
    "isVerified" boolean
);


ALTER TABLE "public"."Jobs" OWNER TO "postgres";


ALTER TABLE "public"."Jobs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Jobs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."PrivacyPolicy" (
    "agreement_id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "version" character varying NOT NULL,
    "ip_address" character varying,
    "agent" character varying,
    "accepted_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."PrivacyPolicy" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."RecruiterBankDetails" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "recruiter_id" "uuid" NOT NULL,
    "account_number" "text" NOT NULL,
    "account_name" "text" NOT NULL,
    "bank_name" "text" NOT NULL,
    "bank_code" "text" NOT NULL,
    "subaccount_code" "text" NOT NULL,
    "is_primary" boolean DEFAULT true,
    "is_verified" boolean DEFAULT false,
    "last_verified_at" timestamp with time zone
);


ALTER TABLE "public"."RecruiterBankDetails" OWNER TO "postgres";


ALTER TABLE "public"."RecruiterBankDetails" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."RecruiterBankDetails_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Recruiters" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "email" "text",
    "number" "text",
    "dob" "date",
    "gender" "text",
    "country" "text",
    "state" "text",
    "uniqueid" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "logo" "text"
);


ALTER TABLE "public"."Recruiters" OWNER TO "postgres";


ALTER TABLE "public"."Recruiters" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Recruiters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Relation" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "recruiter" "uuid",
    "seeker" "uuid"
);


ALTER TABLE "public"."Relation" OWNER TO "postgres";


ALTER TABLE "public"."Relation" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Relation_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Saved" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "unique_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "seeker_id" "uuid" DEFAULT "auth"."uid"(),
    "job_id" "uuid",
    "name" "text"
);


ALTER TABLE "public"."Saved" OWNER TO "postgres";


COMMENT ON TABLE "public"."Saved" IS 'Same as Applicants';



ALTER TABLE "public"."Saved" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Saved_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Seekers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "email" "text" NOT NULL,
    "number" "text",
    "dob" "date",
    "gender" "text",
    "country" "text",
    "state" "text",
    "unique_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "bio" "text"
);


ALTER TABLE "public"."Seekers" OWNER TO "postgres";


COMMENT ON COLUMN "public"."Seekers"."bio" IS 'A short summary for each applicant';



CREATE TABLE IF NOT EXISTS "public"."TermsOfService" (
    "agreement_id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "version" character varying NOT NULL,
    "ip_address" character varying,
    "agent" character varying,
    "accepted_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."TermsOfService" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."conversation_participants" (
    "conversation_id" "uuid" NOT NULL,
    "recruiter" "uuid" NOT NULL,
    "seeker" "uuid" NOT NULL,
    "last_read_message_id" "uuid"
);


ALTER TABLE "public"."conversation_participants" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."conversations" (
    "last_message" "text",
    "last_message_timestamp" timestamp without time zone DEFAULT "now"(),
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."conversations" OWNER TO "postgres";


ALTER TABLE "public"."Seekers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."job seekers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."job_applications_count" AS
 SELECT "Applicants"."job_id",
    "count"(*) AS "applicant_count",
    "count"(*) FILTER (WHERE ("Applicants"."is_confirmed" = true)) AS "confirmed_count"
   FROM "public"."Applicants"
  GROUP BY "Applicants"."job_id";


ALTER TABLE "public"."job_applications_count" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."jobpayments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "job_id" "uuid" NOT NULL,
    "seeker_id" "uuid" NOT NULL,
    "amount" numeric NOT NULL,
    "reference" "text" NOT NULL,
    "status" "text" NOT NULL
);


ALTER TABLE "public"."jobpayments" OWNER TO "postgres";


ALTER TABLE "public"."jobpayments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."jobpayments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "text" "text" NOT NULL,
    "conversation_id" "uuid",
    "read" boolean DEFAULT false,
    "sender_id" "uuid" DEFAULT "auth"."uid"(),
    "receiver_id" "uuid"
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."test_accounts" (
    "id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "password" "text" NOT NULL,
    "type" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "test_accounts_type_check" CHECK (("type" = ANY (ARRAY['seeker'::"text", 'recruiter'::"text"])))
);


ALTER TABLE "public"."test_accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "display_name" "text",
    "email" "text"
);


ALTER TABLE "public"."user" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "uid" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "name" "text",
    "email" "text" DEFAULT "auth"."email"(),
    "type" "text"
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Applicants"
    ADD CONSTRAINT "Applicants_pkey" PRIMARY KEY ("unique_id");



ALTER TABLE ONLY "public"."CompanyInfo"
    ADD CONSTRAINT "CompanyInfo_pkey" PRIMARY KEY ("unique_id");



ALTER TABLE ONLY "public"."Education"
    ADD CONSTRAINT "Education_pkey" PRIMARY KEY ("unique_id");



ALTER TABLE ONLY "public"."Experience"
    ADD CONSTRAINT "Experience_pkey" PRIMARY KEY ("unique_id");



ALTER TABLE ONLY "public"."Jobs"
    ADD CONSTRAINT "Jobs_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."PrivacyPolicy"
    ADD CONSTRAINT "PrivacyPolicy_pkey" PRIMARY KEY ("agreement_id");



ALTER TABLE ONLY "public"."Recruiters"
    ADD CONSTRAINT "Recruiters_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."Recruiters"
    ADD CONSTRAINT "Recruiters_number_key" UNIQUE ("number");



ALTER TABLE ONLY "public"."Recruiters"
    ADD CONSTRAINT "Recruiters_pkey" PRIMARY KEY ("uniqueid");



ALTER TABLE ONLY "public"."Relation"
    ADD CONSTRAINT "Relation_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Saved"
    ADD CONSTRAINT "Saved_pkey" PRIMARY KEY ("unique_id");



ALTER TABLE ONLY "public"."Seekers"
    ADD CONSTRAINT "Seekers_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."Seekers"
    ADD CONSTRAINT "Seekers_number_key" UNIQUE ("number");



ALTER TABLE ONLY "public"."Seekers"
    ADD CONSTRAINT "Seekers_pkey" PRIMARY KEY ("unique_id");



ALTER TABLE ONLY "public"."TermsOfService"
    ADD CONSTRAINT "TermsOfService_pkey" PRIMARY KEY ("agreement_id");



ALTER TABLE ONLY "public"."Agreements"
    ADD CONSTRAINT "agreements_pkey" PRIMARY KEY ("agreement_id");



ALTER TABLE ONLY "public"."conversation_participants"
    ADD CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("recruiter", "seeker");



ALTER TABLE ONLY "public"."conversations"
    ADD CONSTRAINT "conversations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."jobpayments"
    ADD CONSTRAINT "jobpayments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."RecruiterBankDetails"
    ADD CONSTRAINT "recruiter_bank_details_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test_accounts"
    ADD CONSTRAINT "test_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("uid");



ALTER TABLE ONLY "public"."Agreements"
    ADD CONSTRAINT "Agreements_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."Jobs"("uid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."PrivacyPolicy"
    ADD CONSTRAINT "PrivacyPolicy_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."Recruiters"
    ADD CONSTRAINT "Recruiters_uniqueid_fkey" FOREIGN KEY ("uniqueid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Seekers"
    ADD CONSTRAINT "Seekers_unique_id_fkey" FOREIGN KEY ("unique_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."TermsOfService"
    ADD CONSTRAINT "TermsOfService_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."Agreements"
    ADD CONSTRAINT "agreements_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."conversation_participants"
    ADD CONSTRAINT "conversation_participants_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."Applicants"
    ADD CONSTRAINT "public_Applicants_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."Jobs"("uid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Applicants"
    ADD CONSTRAINT "public_Applicants_seeker_id_fkey" FOREIGN KEY ("seeker_id") REFERENCES "public"."Seekers"("unique_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."CompanyInfo"
    ADD CONSTRAINT "public_CompanyInfo_unique_id_fkey" FOREIGN KEY ("unique_id") REFERENCES "public"."Recruiters"("uniqueid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Education"
    ADD CONSTRAINT "public_Education_unique_id_fkey" FOREIGN KEY ("unique_id") REFERENCES "public"."Seekers"("unique_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Experience"
    ADD CONSTRAINT "public_Experience_unique_id_fkey" FOREIGN KEY ("unique_id") REFERENCES "public"."Seekers"("unique_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Jobs"
    ADD CONSTRAINT "public_Jobs_recruiter_fkey" FOREIGN KEY ("recruiter") REFERENCES "public"."Recruiters"("uniqueid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Relation"
    ADD CONSTRAINT "public_Relation_recruiter_fkey" FOREIGN KEY ("recruiter") REFERENCES "public"."Recruiters"("uniqueid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Relation"
    ADD CONSTRAINT "public_Relation_seeker_fkey" FOREIGN KEY ("seeker") REFERENCES "public"."Seekers"("unique_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Saved"
    ADD CONSTRAINT "public_Saved_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "public"."Jobs"("uid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Saved"
    ADD CONSTRAINT "public_Saved_seeker_id_fkey" FOREIGN KEY ("seeker_id") REFERENCES "public"."Seekers"("unique_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."conversation_participants"
    ADD CONSTRAINT "public_conversation_participants_recruiter_fkey" FOREIGN KEY ("recruiter") REFERENCES "public"."Recruiters"("uniqueid");



ALTER TABLE ONLY "public"."conversation_participants"
    ADD CONSTRAINT "public_conversation_participants_seeker_fkey" FOREIGN KEY ("seeker") REFERENCES "public"."Seekers"("unique_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "public_users_uid_fkey" FOREIGN KEY ("uid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."RecruiterBankDetails"
    ADD CONSTRAINT "recruiter_bank_details_recruiter_id_fkey" FOREIGN KEY ("recruiter_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."test_accounts"
    ADD CONSTRAINT "test_accounts_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable all access for authenticated users" ON "public"."test_accounts" USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."Seekers" FOR INSERT TO "authenticated" WITH CHECK (true);



ALTER TABLE "public"."test_accounts" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."messages";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";









































































































































































































GRANT ALL ON FUNCTION "public"."create_user_on_signup"() TO "anon";
GRANT ALL ON FUNCTION "public"."create_user_on_signup"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_user_on_signup"() TO "service_role";
























GRANT ALL ON TABLE "public"."Agreements" TO "anon";
GRANT ALL ON TABLE "public"."Agreements" TO "authenticated";
GRANT ALL ON TABLE "public"."Agreements" TO "service_role";



GRANT ALL ON TABLE "public"."Applicants" TO "anon";
GRANT ALL ON TABLE "public"."Applicants" TO "authenticated";
GRANT ALL ON TABLE "public"."Applicants" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Applicants_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Applicants_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Applicants_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."CompanyInfo" TO "anon";
GRANT ALL ON TABLE "public"."CompanyInfo" TO "authenticated";
GRANT ALL ON TABLE "public"."CompanyInfo" TO "service_role";



GRANT ALL ON SEQUENCE "public"."CompanyInfo_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CompanyInfo_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CompanyInfo_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Education" TO "anon";
GRANT ALL ON TABLE "public"."Education" TO "authenticated";
GRANT ALL ON TABLE "public"."Education" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Education_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Education_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Education_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Experience" TO "anon";
GRANT ALL ON TABLE "public"."Experience" TO "authenticated";
GRANT ALL ON TABLE "public"."Experience" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Experience_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Experience_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Experience_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Jobs" TO "anon";
GRANT ALL ON TABLE "public"."Jobs" TO "authenticated";
GRANT ALL ON TABLE "public"."Jobs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Jobs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Jobs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Jobs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."PrivacyPolicy" TO "anon";
GRANT ALL ON TABLE "public"."PrivacyPolicy" TO "authenticated";
GRANT ALL ON TABLE "public"."PrivacyPolicy" TO "service_role";



GRANT ALL ON TABLE "public"."RecruiterBankDetails" TO "anon";
GRANT ALL ON TABLE "public"."RecruiterBankDetails" TO "authenticated";
GRANT ALL ON TABLE "public"."RecruiterBankDetails" TO "service_role";



GRANT ALL ON SEQUENCE "public"."RecruiterBankDetails_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."RecruiterBankDetails_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."RecruiterBankDetails_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Recruiters" TO "anon";
GRANT ALL ON TABLE "public"."Recruiters" TO "authenticated";
GRANT ALL ON TABLE "public"."Recruiters" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Recruiters_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Recruiters_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Recruiters_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Relation" TO "anon";
GRANT ALL ON TABLE "public"."Relation" TO "authenticated";
GRANT ALL ON TABLE "public"."Relation" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Relation_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Relation_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Relation_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Saved" TO "anon";
GRANT ALL ON TABLE "public"."Saved" TO "authenticated";
GRANT ALL ON TABLE "public"."Saved" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Saved_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Saved_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Saved_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Seekers" TO "anon";
GRANT ALL ON TABLE "public"."Seekers" TO "authenticated";
GRANT ALL ON TABLE "public"."Seekers" TO "service_role";



GRANT ALL ON TABLE "public"."TermsOfService" TO "anon";
GRANT ALL ON TABLE "public"."TermsOfService" TO "authenticated";
GRANT ALL ON TABLE "public"."TermsOfService" TO "service_role";



GRANT ALL ON TABLE "public"."conversation_participants" TO "anon";
GRANT ALL ON TABLE "public"."conversation_participants" TO "authenticated";
GRANT ALL ON TABLE "public"."conversation_participants" TO "service_role";



GRANT ALL ON TABLE "public"."conversations" TO "anon";
GRANT ALL ON TABLE "public"."conversations" TO "authenticated";
GRANT ALL ON TABLE "public"."conversations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."job seekers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."job seekers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."job seekers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."job_applications_count" TO "anon";
GRANT ALL ON TABLE "public"."job_applications_count" TO "authenticated";
GRANT ALL ON TABLE "public"."job_applications_count" TO "service_role";



GRANT ALL ON TABLE "public"."jobpayments" TO "anon";
GRANT ALL ON TABLE "public"."jobpayments" TO "authenticated";
GRANT ALL ON TABLE "public"."jobpayments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."jobpayments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."jobpayments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."jobpayments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON TABLE "public"."test_accounts" TO "anon";
GRANT ALL ON TABLE "public"."test_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."test_accounts" TO "service_role";



GRANT ALL ON TABLE "public"."user" TO "anon";
GRANT ALL ON TABLE "public"."user" TO "authenticated";
GRANT ALL ON TABLE "public"."user" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























